### ISSUE TITLE
Use number input for quantity

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Starter-kit-for-Umbraco#2]
It would be better to use HTML5 number input `<input type="number" />` for quantities, so mobile and tablets display a numeric keypad.

Furthermore by adding the pattern attribute, iOS will display a truly numeric keypad.
http://bradfrost.com/blog/mobile/better-numerical-inputs-for-mobile-forms/

`<input type="number" pattern="[0-9]*" min="1" />`

without the pattern attribute, iOS still show a numeric keypad, but as the standard numeric keypad on iOS: http://danielfriesen.name/blog/2013/09/19/input-type-number-and-ios-numeric-keypad/

Could be useful if someone demonstrate the demo site for clients on mobile and tablet :)

**Comment by andersburla** [comment]
Sounds sweet. How about a pull request? :)
